### ISSUE TITLE
clang-16 crashes

### ISSUE THREAD

**Issue by anders-wind** [twig-energy/stronk#37]
When compiling with clang-16's frontend crashes. Figure out why that is and create a bug report at llvm.

Pull request with info: #36 

Clang-17 now works so we can migrate to it.

**Comment by anders-wind** [comment]
Link to llvm-project issue: https://github.com/llvm/llvm-project/issues/62344

**Comment by anders-wind** [comment]
Clang-17 fixes the problem again. I hope that we will end up with clang-16 support as well

**Comment by anders-wind** [comment]
the llvm group decided not to fix the issue in clang-16 but clang-17 support works so that will have to do 👍

**Comment by anders-wind** [comment]
Use https://github.com/KyleMayes/install-llvm-action to install clang-17 and then use that by default.

**Comment by mikaellindemann** [comment]
Closing, since llvm did never fix the issue in clang-16.
